apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token-file
            - /etc/cloudflared/token
          volumeMounts:
            - name: token
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: token
          secret:
            secretName: cloudflared-token
            items:
              - key: token
                path: token
